name: Build Tauri App
description: 构建 Tauri 应用的共享步骤

inputs:
  platform:
    description: '构建平台 (windows, windows-arm64, linux, linux-arm64, macos, macos-intel)'
    required: true
  signing-private-key:
    description: Tauri 签名私钥
    required: true
  signing-private-key-password:
    description: Tauri 签名私钥密码
    required: true

runs:
  using: composite
  steps:
    - name: 安装系统依赖 (Install system dependencies)
      if: startsWith(inputs.platform, 'linux')
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: 安装 Rust (Install Rust)
      uses: dtolnay/rust-toolchain@stable

    - name: Rust 缓存 (Rust cache)
      uses: swatinem/rust-cache@v2
      with:
        workspaces: ./src-tauri -> target

    - name: 安装 pnpm (Install pnpm)
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: 安装 Node.js (Install Node.js)
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm

    - name: 安装前端依赖 (Install frontend dependencies)
      shell: bash
      run: pnpm install

    - name: 构建应用 (Build app)
      shell: bash
      env:
        TAURI_SIGNING_PRIVATE_KEY: ${{ inputs.signing-private-key }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ inputs.signing-private-key-password }}
      run: pnpm tauri build
